from app import create_app
from models import db, Prompt, User


def seed_prompts(default_user_id):
    example = [
        {
            "title": "Animal",
            "description": "A detailed prompt to generate realistic animal imagery.",
            "tags": "animal,photorealistic",
            "image_url": "https://picsum.photos/400/600",
            "downloads": 210,
            "average_rating": 4.8,
        },
        {
            "title": "Futuristic Samurai",
            "description": "Stylised futuristic samurai scene with neon lights.",
            "tags": "samurai,cyberpunk,neon",
            "image_url": "https://picsum.photos/400/500",
            "downloads": 180,
            "average_rating": 4.5,
        },
        {
            "title": "AI Dream Landscape",
            "description": "Surreal dream-like landscapes generated by AI.",
            "tags": "landscape,dream,ai",
            "image_url": "https://picsum.photos/400/700",
            "downloads": 350,
            "average_rating": 4.9,
        },
        {
            "title": "Cyberpunk Cityscape",
            "description": "Crowded cyberpunk city at night with neon signs.",
            "tags": "city,cyberpunk,night",
            "image_url": "https://picsum.photos/400/600",
            "downloads": 200,
            "average_rating": 3.8,
        },
        {
            "title": "Photorealistic",
            "description": "High-quality photorealistic render prompts.",
            "tags": "photorealistic,high-quality",
            "image_url": "https://picsum.photos/400/400",
            "downloads": 4050,
            "average_rating": 4.8,
        },
        {
            "title": "Quality",
            "description": "Short quality-check prompts for testing output.",
            "tags": "test,quality",
            "image_url": "https://picsum.photos/400/300",
            "downloads": 30,
            "average_rating": 3.0,
        },
    ]

    for p in example:
        exists = (
            Prompt.query.filter_by(title=p["title"], creator=default_user_id).first()
        )
        if not exists:
            prompt = Prompt(
                title=p["title"],
                image_url=p["image_url"],
                creator=default_user_id,
                rating=p.get("average_rating", 0.0),
            )
            db.session.add(prompt)
    db.session.commit()


def main():
    app = create_app()
    with app.app_context():
        # Create tables for the current models
        db.create_all()

        # Ensure a default user exists to assign as the prompt creator
        default_username = "seed_user"
        default_email = "seed@example.com"
        user = User.query.filter_by(username=default_username).first()
        if not user:
            user = User(username=default_username, email=default_email, password_hash="seed")
            db.session.add(user)
            db.session.commit()

        seed_prompts(user.id)
        print("Database created/updated and sample prompts seeded.")


if __name__ == "__main__":
    main()
